---
title: "leaflet"
author: "Vincenzo Palazeti"
date: "2022-08-04"
categories: [code]
---



<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
    integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
    crossorigin=""/>

<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
    integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
    crossorigin=""></script>


<script src="/assets/data/tracts.js"></script>
<script src="/assets/data/boarder.js"></script>


<style>

  #map {
    height: 600px;
    /*width: 700px;*/
  }
</style>



My goal is to create geojsons from a Postgis database.


<div id = "map"></div>
<script>

var map = L.map('map', {
    maxZoom: 15,
    minZoom: 10,
    maxBounds: [
        //south west
        [39.28, -87.15],
        //north east
        [40.28, -85.15]]
    }).setView([39.78,-86.15], 11);



L.tileLayer('https://api.maptiler.com/maps/basic/{z}/{x}/{y}.png?key=6TdD4fY5e1atR7f2ObxW', {
  attribution : '<a href="https://www.maptiler.com/copyright/" target="_blank">&copy; MapTiler</a> <a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; OpenStreetMap contributors</a>'
}).addTo(map);




// Functions

// Highlight feature options
//     fillColor: "#ff7800",
//     color: "#000",
//     weight: 1,
//     opacity: 1,
//     fillOpacity: 0.8

function highlightFeature(e) {
    var layer = e.target;

    layer.setStyle({
        weight: 3,
        fillColor: '#0400ff',
        color: '',
        dashArray: '',
        opacity: 0,
        fillOpacity: 0.4
    });

    if (!L.Browser.ie && !L.Browser.opera && !L.Browser.edge) {
        layer.bringToFront();
    }
}

function resetHighlight(e) {
    geojson_tracts.resetStyle(e.target);
}

function zoomToFeature(e) {
    map.fitBounds(e.target.getBounds());
}


function onEachFeature(feature, layer) {
    layer.on({
        mouseover: highlightFeature,
        mouseout: resetHighlight,
        click: zoomToFeature
    });
}

// Styles

// Kept the tracts & dissolved geojson the same color
// kept the track outlines barely visible, same color just a little darker
// they highlight a different color & disappear
//


// opacity refers to the boarder
var boarderStyle = {
    "color": "#ff7800",
    "weight": 3,
    "opacity": 0.7
};


var tractStyle = {
    "color": "#ff7800",
    "weight": 0.2,
    "opacity": 1
};

L.geoJSON(boarder, {
    style: boarderStyle
    }).addTo(map);

// L.geoJSON(tracts).addTo(map);

geojson_tracts = L.geoJson(tracts, {
    onEachFeature: onEachFeature,
    style: tractStyle
    }).addTo(map);



</script>


<div id="example"></div>

Things to keep in mind:
