project:
  type: website

website:
  title: "Site"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  comments:
    hypothesis: true        

format:
  html:
    theme: sandstone-light
    css: styles.css
    # highlight-style: kate

