project:
  type: website

website:
  title: cookbook
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/vinnie-palazeti
      - icon: twitter
        href: https://twitter.com       

format:
  html:
    theme: sandstone-light
    css: styles.css

