project:
  type: website

website:
  title: "Vincenzo Palazeti"
  navbar:
    right:
      - href: index.qmd
        text: home
      - about.qmd
      - resume.qmd
      - posts.qmd
      - icon: github
        href: https://github.com/vinnie-palazeti
      - icon: twitter
        href: https://twitter.com
  page-footer:
    background: light
    left:
      - "Copyright 2022, Vincenzo Palazeti"
    right:
      - icon: github
        href: https://github.com/vinnie-palazeti
      - icon: twitter
        href: https://twitter.com
  reader-mode: true

format:
  html:
    page-layout: full
    theme:
      - red_theme.scss
    mainfont: Nunito
    toc: true
