---
title: GLM
date: "2023-12-16"
categories: [statistics, regression, log odds]
---

## CATE

The conditional average treatment effect

$$ 
\text{CATE} = \mathbb{E}[\text{Pr}(\text{Y}_i = 1 \ |\ \text{X}_i = 1) \ - \ \text{Pr}(\text{Y}_i = 1 \ |\ \text{X}_i = 0) \ | \ \text{Z}_i = z]
$$

```{r}
library(data.table)

# covariates
X <- rbinom(1000,1,0.5)
Z <- rbinom(1000,1,0.4)
# data generating process
mu <- -0.5 + 0.5*X + X*(-1.0*Z) + rnorm(1000,0,0.1)
# logistic function
theta <- exp(mu) / (1 + exp(mu))
# outcome
Y <- rbinom(1000, 1, theta)
data <- data.table(Y=Y, X=X, Z=Z)

# model
logit <- glm(Y ~ X + X*Z, data=data, family = binomial(link="logit"))

# data with both values of X
Y1 <- data.table(Y = data$Y, X = 1, X = data$Z)
Y0 <- data.table(Y = data$Y, X = 0, X = data$Z)

# expected value at each level of X# 
EY1 <- predict(logit, newdata=Y1, type='response')
EY0 <- predict(logit, newdata=Y0, type='response')

# create columns
data[, ':=' ('EY1' = EY1, 'EY0' = EY0)]

# calculate estimand at different covariate values
data[, .('CATE' = mean(EY1 - EY0)), by=Z]
```



```{r}
library(marginaleffects)

mod <- glm(vs ~ hp * am, data = mtcars, family=binomial)

comparisons(
    mod, 
    variables='am', 
    newdata=datagrid(hp=c(100,120))
)

comparisons(
    mod, 
    variables='am', 
    newdata=datagrid(hp=c(100,120)),
    hypothesis='b1 = b2'
)

```